// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from "flatbuffers";

import { FieldTypeStruct } from "../document/field-type-struct.js";
import { AggregationTypeEnum } from "../enum/aggregation-type-enum.js";
import { OrderTypeEnum } from "../enum/order-type-enum.js";

/**
 * Data field structure.
 */
export class FieldStruct {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): FieldStruct {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsFieldStruct(
    bb: flatbuffers.ByteBuffer,
    obj?: FieldStruct,
  ): FieldStruct {
    return (obj || new FieldStruct()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb,
    );
  }

  static getSizePrefixedRootAsFieldStruct(
    bb: flatbuffers.ByteBuffer,
    obj?: FieldStruct,
  ): FieldStruct {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new FieldStruct()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb,
    );
  }

  name(): string | null;
  name(
    optionalEncoding: flatbuffers.Encoding,
  ): string | Uint8Array | null;
  name(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  description(): string | null;
  description(
    optionalEncoding: flatbuffers.Encoding,
  ): string | Uint8Array | null;
  description(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  origin(): string | null;
  origin(
    optionalEncoding: flatbuffers.Encoding,
  ): string | Uint8Array | null;
  origin(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  clause(): string | null;
  clause(
    optionalEncoding: flatbuffers.Encoding,
  ): string | Uint8Array | null;
  clause(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  type(obj?: FieldTypeStruct): FieldTypeStruct | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? (obj || new FieldTypeStruct()).__init(
          this.bb!.__indirect(this.bb_pos + offset),
          this.bb!,
        )
      : null;
  }

  aggregation(): AggregationTypeEnum {
    const offset = this.bb!.__offset(this.bb_pos, 14);
    return offset
      ? this.bb!.readInt8(this.bb_pos + offset)
      : AggregationTypeEnum.None;
  }

  order(): OrderTypeEnum {
    const offset = this.bb!.__offset(this.bb_pos, 16);
    return offset
      ? this.bb!.readInt8(this.bb_pos + offset)
      : OrderTypeEnum.None;
  }

  static startFieldStruct(builder: flatbuffers.Builder) {
    builder.startObject(7);
  }

  static addName(
    builder: flatbuffers.Builder,
    nameOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(0, nameOffset, 0);
  }

  static addDescription(
    builder: flatbuffers.Builder,
    descriptionOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(1, descriptionOffset, 0);
  }

  static addOrigin(
    builder: flatbuffers.Builder,
    originOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(2, originOffset, 0);
  }

  static addClause(
    builder: flatbuffers.Builder,
    clauseOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(3, clauseOffset, 0);
  }

  static addType(
    builder: flatbuffers.Builder,
    typeOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(4, typeOffset, 0);
  }

  static addAggregation(
    builder: flatbuffers.Builder,
    aggregation: AggregationTypeEnum,
  ) {
    builder.addFieldInt8(5, aggregation, AggregationTypeEnum.None);
  }

  static addOrder(
    builder: flatbuffers.Builder,
    order: OrderTypeEnum,
  ) {
    builder.addFieldInt8(6, order, OrderTypeEnum.None);
  }

  static endFieldStruct(
    builder: flatbuffers.Builder,
  ): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }
}
