// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from "flatbuffers";

import { FieldStruct } from "../document/field-struct.js";
import { TableTypeEnum } from "../enum/table-type-enum.js";

/**
 * Table structure.
 */
export class TableStruct {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): TableStruct {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsTableStruct(
    bb: flatbuffers.ByteBuffer,
    obj?: TableStruct,
  ): TableStruct {
    return (obj || new TableStruct()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb,
    );
  }

  static getSizePrefixedRootAsTableStruct(
    bb: flatbuffers.ByteBuffer,
    obj?: TableStruct,
  ): TableStruct {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new TableStruct()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb,
    );
  }

  name(): string | null;
  name(
    optionalEncoding: flatbuffers.Encoding,
  ): string | Uint8Array | null;
  name(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  description(): string | null;
  description(
    optionalEncoding: flatbuffers.Encoding,
  ): string | Uint8Array | null;
  description(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  type(): TableTypeEnum {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset
      ? this.bb!.readInt8(this.bb_pos + offset)
      : TableTypeEnum.Table;
  }

  identifier(): string | null;
  identifier(
    optionalEncoding: flatbuffers.Encoding,
  ): string | Uint8Array | null;
  identifier(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null;
  }

  fields(index: number, obj?: FieldStruct): FieldStruct | null {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset
      ? (obj || new FieldStruct()).__init(
          this.bb!.__indirect(
            this.bb!.__vector(this.bb_pos + offset) + index * 4,
          ),
          this.bb!,
        )
      : null;
  }

  fieldsLength(): number {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
  }

  static startTableStruct(builder: flatbuffers.Builder) {
    builder.startObject(5);
  }

  static addName(
    builder: flatbuffers.Builder,
    nameOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(0, nameOffset, 0);
  }

  static addDescription(
    builder: flatbuffers.Builder,
    descriptionOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(1, descriptionOffset, 0);
  }

  static addType(builder: flatbuffers.Builder, type: TableTypeEnum) {
    builder.addFieldInt8(2, type, TableTypeEnum.Table);
  }

  static addIdentifier(
    builder: flatbuffers.Builder,
    identifierOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(3, identifierOffset, 0);
  }

  static addFields(
    builder: flatbuffers.Builder,
    fieldsOffset: flatbuffers.Offset,
  ) {
    builder.addFieldOffset(4, fieldsOffset, 0);
  }

  static createFieldsVector(
    builder: flatbuffers.Builder,
    data: flatbuffers.Offset[],
  ): flatbuffers.Offset {
    builder.startVector(4, data.length, 4);
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i]);
    }
    return builder.endVector();
  }

  static startFieldsVector(
    builder: flatbuffers.Builder,
    numElems: number,
  ) {
    builder.startVector(4, numElems, 4);
  }

  static endTableStruct(
    builder: flatbuffers.Builder,
  ): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createTableStruct(
    builder: flatbuffers.Builder,
    nameOffset: flatbuffers.Offset,
    descriptionOffset: flatbuffers.Offset,
    type: TableTypeEnum,
    identifierOffset: flatbuffers.Offset,
    fieldsOffset: flatbuffers.Offset,
  ): flatbuffers.Offset {
    TableStruct.startTableStruct(builder);
    TableStruct.addName(builder, nameOffset);
    TableStruct.addDescription(builder, descriptionOffset);
    TableStruct.addType(builder, type);
    TableStruct.addIdentifier(builder, identifierOffset);
    TableStruct.addFields(builder, fieldsOffset);
    return TableStruct.endTableStruct(builder);
  }
}
