#!/bin/bash

# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

git config --global --add safe.directory /workspaces/HDML-Utilities
git config core.sshCommand "$(which ssh) -i /home/.ssh/hdml.github"